version: "2"
services:
  jenkins-2024:
    image: marksugar/jenkins:2.461-almalinux-58080-ansible-202408
    container_name: jenkins2024
    restart: always
    network_mode: host
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai # 时区1
    volumes:
      - /etc/localtime:/etc/localtime:ro # 时区2
      - /data/2024_docker_jenkins/jenkins_home:/var/jenkins_home # jenkins家目录映射
      ## chown -R 1000:1000 /data/2024_docker_jenkins/jenkins_home,启动后重新在chown一次即可启动
      - /data/2024_docker_jenkins/ansiblefile:/etc/ansible # jenkins ansible文件映射
      #- /data/2024_docker_jenkins/latest_war_package/jenkins.war:/usr/share/jenkins/jenkins.war # jenkins war新包挂载
    ports:
      - 58080:58080
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
    mem_limit: 4096M
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
